//using System.Collections;
//using System.Collections.Generic;
using UnityEngine;
//using UnityEngine.PlayerLoop;

public enum Ore_TB
{
    None,
    Ore_A,
    Ore_B,
    Ore_C,
    Ore_D,
    Ore_E,
    Ore_F,
    Ore_G,
    Ore_H,
}

public class Ore : MonoBehaviour
{
   
    public int ore_a = 0;          //zÎA‚Ì‰Šú‰»
    public int ore_b = 0;          //zÎB‚Ì‰Šú‰»
    public int ore_c = 0;          //zÎC‚Ì‰Šú‰»
    private bool Updeta = false;     //ƒAƒbƒvƒf[ƒg‚ğfalse‚É‰Šú‰»
    private bool Updeta_t = false; //zÎ‚ğ‚Ù‚©‚ÌƒXƒNƒŠƒvƒg‚É“n‚·                           

    public Ore_TB m_type = Ore_TB.None;
    // Update is called once per frame

    public void Start()
    {

    }
    void Update()
    {
        if (Updeta_t)
        {
            if (Updeta == true)
            {
                ore_a = 0;          //zÎA‚Ì‰Šú‰»
                ore_b = 0;          //zÎB‚Ì‰Šú‰»
                ore_c = 0;          //zÎC‚Ì‰Šú‰»

                //ƒf[ƒ^‚ğ“n‚·ˆ—‚ğs‚¤
                SoundManager.Instance.Play_SE(0, 18);
                //ƒfƒXƒgƒƒCˆ—
                Destroy(gameObject);
            }

        }
        else
        {
            //Player_HP‚ğƒAƒbƒvƒf[ƒg‚µ‚Ä‚¢‚­
            if (Updeta == true)
            {
                Ore_processing();
            }
        }
    }
    void Ore_processing()
    {
        Ore ore = this.gameObject.GetComponent<Ore>();
        switch (ore.m_type)
        {
            //zÎA‚ªˆ—‚³‚ê‚Ä‚¢‚é‚©Œ©‚é
            case Ore_TB.Ore_A:
                ore_a = 1;   //”½ËzÎ1ŒÂ—^‚¦‚é
                ore_b = 2;      //d—ÍzÎ2ŒÂ—^‚¦‚é
                GameMainContol.Instance.addCrystal(ore_a, ore_b, ore_c);
                Updeta_t = true; //ˆ—‚ÉˆÚ“®
                break;
            //zÎB‚ªˆ—‚³‚ê‚Ä‚¢‚é‚©Œ©‚é
            case Ore_TB.Ore_B:
                ore_a = 2;      //”½ËzÎ2ŒÂ—^‚¦‚é
                ore_b = 1;      //d—ÍzÎ1ŒÂ—^‚¦‚é
                GameMainContol.Instance.addCrystal(ore_a, ore_b, ore_c);
                Updeta_t = true; //ˆ—‚ÉˆÚ“®
                break;
            //zÎC‚ªˆ—‚³‚ê‚Ä‚¢‚é‚©Œ©‚é
            case Ore_TB.Ore_C:
                ore_a = 1;      //”½ËzÎ1ŒÂ—^‚¦‚é
                ore_b = 3;      //d—ÍzÎ3ŒÂ—^‚¦‚é
                GameMainContol.Instance.addCrystal(ore_a, ore_b, ore_c);
                Updeta_t = true; //ˆ—‚ÉˆÚ“®
                break;
            //zÎD‚ªˆ—‚³‚ê‚Ä‚¢‚é‚©Œ©‚é
            case Ore_TB.Ore_D:
                ore_a = 3;      //”½ËzÎ3ŒÂ—^‚¦‚é
                ore_b = 1;      //d—ÍzÎ1ŒÂ—^‚¦‚é
                GameMainContol.Instance.addCrystal(ore_a, ore_b, ore_c);
                Updeta_t = true; //ˆ—‚ÉˆÚ“®
                break;
            //zÎE‚ªˆ—‚³‚ê‚Ä‚¢‚é‚©Œ©‚é
            case Ore_TB.Ore_E:
                ore_a = 1;   //”½ËzÎ1ŒÂ—^‚¦‚é
                ore_b = 1;      //d—ÍzÎ1ŒÂ—^‚¦‚é
                ore_c = 2;      //”š”­zÎ2ŒÂ—^‚¦‚é
                GameMainContol.Instance.addCrystal(ore_a, ore_b, ore_c);
                Updeta_t = true; //ˆ—‚ÉˆÚ“®
                break;
            //zÎF‚ªˆ—‚³‚ê‚Ä‚¢‚é‚©Œ©‚é
            case Ore_TB.Ore_F:
                ore_a = 1;      //”½ËzÎ1ŒÂ—^‚¦‚é
                ore_b = 0;      //d—ÍzÎ0ŒÂ—^‚¦‚é
                ore_c = 3;      //”š”­zÎ3ŒÂ—^‚¦‚é
                GameMainContol.Instance.addCrystal(ore_a, ore_b, ore_c);
                Updeta_t = true; //ˆ—‚ÉˆÚ“®
                break;
            //zÎG‚ªˆ—‚³‚ê‚Ä‚¢‚é‚©Œ©‚é
            case Ore_TB.Ore_G:
                ore_a = 1;      //”½ËzÎ1ŒÂ—^‚¦‚é
                ore_b = 2;      //d—ÍzÎ2ŒÂ—^‚¦‚é
                ore_c = 1;      //”š”­zÎ1ŒÂ—^‚¦‚é
                GameMainContol.Instance.addCrystal(ore_a, ore_b, ore_c);
                Updeta_t = true; //ˆ—‚ÉˆÚ“®
                break;
            //zÎH‚ªˆ—‚³‚ê‚Ä‚¢‚é‚©Œ©‚é
            case Ore_TB.Ore_H:
                ore_a = 2;      //”½ËzÎ2ŒÂ—^‚¦‚é
                ore_b = 0;      //d—ÍzÎ0ŒÂ—^‚¦‚é
                ore_c = 2;      //”š”­zÎ2ŒÂ—^‚¦‚é
                GameMainContol.Instance.addCrystal(ore_a, ore_b, ore_c);
                Updeta_t = true; //ˆ—‚ÉˆÚ“®
                break;
        }
    }


    //•¨‚ª’Ê‰ß‚µ‚½‚©Œ©‚é
    void OnTriggerEnter2D(Collider2D collision2d)
    {
        //Debug.Log("zÎƒhƒƒbƒv");
        //Debug.Log("•¨‚É‚ ‚½‚Á‚½a");
        //ƒvƒŒƒCƒ„[‚ª“–‚½‚Á‚Ä‚¢‚é‚©‚Ì”»’è
        if (collision2d.gameObject.CompareTag("P_A"))
        {
            Debug.Log("ƒvƒŒƒCƒ„[‚ğŠm”F");
            Updeta = true;
        }
    }
}
