using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Ore : MonoBehaviour
{
   
    public float ore_a = 0;          //zÎA‚Ì‰Šú‰»
    public float ore_b = 0;          //zÎB‚Ì‰Šú‰»
    public float ore_c = 0;          //zÎC‚Ì‰Šú‰»
    public float ore_d = 0;          //zÎD‚Ì‰Šú‰»
    private bool Updeta = false;     //ƒAƒbƒvƒf[ƒg‚ğfalse‚É‰Šú‰»
    private bool Ore_A = false;      //zÎA‚Ìfalse‚É‰Šú‰»
    private bool Ore_B = false;      //zÎA‚Ìfalse‚É‰Šú‰»
    private bool Ore_C = false;      //zÎA‚Ìfalse‚É‰Šú‰»
    private bool Ore_D = false;      //zÎA‚Ìfalse‚É‰Šú‰»

    // Start is called before the first frame update
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {
        //Player_HP‚ğƒAƒbƒvƒf[ƒg‚µ‚Ä‚¢‚­
        if (Updeta == true)
        {
            //zÎA‚ªˆ—‚³‚ê‚Ä‚¢‚é‚©Œ©‚é
            if (Ore_A == true)
            {
                ore_a = 1;@@@//”½ËzÎ1ŒÂ—^‚¦‚é
                ore_b = 2;      //d—ÍzÎ2ŒÂ—^‚¦‚é
                Ore_A = false;  //AzÎ
            }
            //zÎB‚ªˆ—‚³‚ê‚Ä‚¢‚é‚©Œ©‚é
            if (Ore_B == true)
            {
                ore_a = 2;      //”½ËzÎ2ŒÂ—^‚¦‚é
                ore_b = 1;      //d—ÍzÎ1ŒÂ—^‚¦‚é
                Ore_B = false;  //BzÎ
            }
            //zÎC‚ªˆ—‚³‚ê‚Ä‚¢‚é‚©Œ©‚é
            if (Ore_C == true)
            {
                ore_a = 1;      //”½ËzÎ1ŒÂ—^‚¦‚é
                ore_b = 3;      //d—ÍzÎ3ŒÂ—^‚¦‚é
                Ore_C = false;  //CzÎ
            }
            //zÎD‚ªˆ—‚³‚ê‚Ä‚¢‚é‚©Œ©‚é
            if (Ore_D == true)
            {
                ore_a = 3;      //”½ËzÎ3ŒÂ—^‚¦‚é
                ore_b = 1;      //d—ÍzÎ1ŒÂ—^‚¦‚é
                Ore_D = false;  //DzÎ
            }
            Updeta = false;     //update‚Ìfalse‚É‚·‚é
        }
        else
        {
            ore_a = 0;          //A‚ÌzÎ‚Ìó‚¯“n‚µ‚ğ‰Šú‚É–ß‚·
            ore_b = 0;          //B‚ÌzÎ‚Ìó‚¯“n‚µ‚ğ‰Šú‚É–ß‚·
            ore_c = 0;          //C‚ÌzÎ‚Ìó‚¯“n‚µ‚ğ‰Šú‚É–ß‚·
            ore_d = 0;          //D‚ÌzÎ‚Ìó‚¯“n‚µ‚ğ‰Šú‚É–ß‚·
        }

    }
    //•¨‚ª’Ê‰ß‚µ‚½‚©Œ©‚é
    void OnCollisionEnter2D(Collision2D collision2d)
    {
        //Debug.Log("•¨‚É‚ ‚½‚Á‚½");
        //ƒvƒŒƒCƒ„[‚ª“–‚½‚Á‚Ä‚¢‚é‚©‚Ì”»’è
        if (collision2d.gameObject.CompareTag("Player"))
        {
            Debug.Log("ƒvƒŒƒCƒ„[‚ğŠm”F");
            //‚Ç‚ÌzÎ‚ğ‚½‚½‚¢‚½‚Ì‚©‚Ì”»’èiAzÎj
            if (gameObject.CompareTag("Ore_A"))
            {
                //zÎ‚ğÁ‚·
                Destroy(gameObject);
                //zÎA‚ğtrue‚É‚·‚é
                Ore_A = true;
                //Updata‚ğtrue‚É‚·‚é
                Updeta = true;
                Debug.Log("Ore_A‚ğŠm”F");
            }
            //‚Ç‚ÌzÎ‚ğ‚½‚½‚¢‚½‚Ì‚©‚Ì”»’èiBzÎj
            if (gameObject.CompareTag("Ore_B"))
            {
                //zÎ‚ğÁ‚·
                Destroy(gameObject);
                //zÎB‚ğtrue‚É‚·‚é
                Ore_B = true;
                //Updata‚ğtrue‚É‚·‚é
                Updeta = true;
            }
            //‚Ç‚ÌzÎ‚ğ‚½‚½‚¢‚½‚Ì‚©‚Ì”»’èiCzÎj
            if (gameObject.CompareTag("Ore_C"))
            {
                //zÎ‚ğÁ‚·
                Destroy(gameObject);
                //zÎC‚ğtrue‚É‚·‚é
                Ore_C = true;
                //Updata‚ğtrue‚É‚·‚é
                Updeta = true;
            }
            //‚Ç‚ÌzÎ‚ğ‚½‚½‚¢‚½‚Ì‚©‚Ì”»’èiDzÎj
            if (gameObject.CompareTag("Ore_D"))
            if (gameObject.CompareTag("Ore_D"))
            {
                //zÎ‚ğÁ‚·
                Destroy(gameObject);
                //zÎD‚ğtrue‚É‚·‚é
                Ore_D = true;
                //Updata‚ğtrue‚É‚·‚é
                Updeta = true;
            }
        }
    }
}
